## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "main"

# Setups
format="""\
${custom.git_remote}$git_status$directory$git_branch\
$rust$golang$lua\
$container$character\
"""
add_newline = false

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
perl.disabled = true
package.disabled = true
nodejs.disabled = true
java.disabled = true

[custom.git_remote]
description = "show name of the git remote (works for github and gitlab)"
command = "basename $(git remote get-url origin) .git"
when = "git rev-parse --is-inside-work-tree 2>/dev/null"
shell = ["sh"]
format = "[](bg:none fg:base)[[$output](bg:8 $style)](bg:8 fg:15)[ ](bg:none fg:base)"
style = "white"

[container]
format='[$symbol \[$name\]]($style) '
symbol="⬢"
style="blue dimmed"

[rust]
format="[](bg:none fg:base)[with [$symbol](bg:8 $style)](bg:8 fg:15)[ ](bg:none fg:base)"
symbol="rust"
style="bright-yellow"

[golang]
format="[](bg:none fg:base)[with [$symbol](bg:8 $style)](bg:8 fg:15)[ ](bg:none fg:base)"
symbol="go"
style="cyan"

[lua]
format="[](bg:none fg:base)[with [$symbol](bg:8 $style)](bg:8 fg:15)[ ](bg:none fg:base)"
symbol="lua"
style="blue"

[deno]
format="[](bg:none fg:base)[with [$symbol](bg:8 $style)](bg:8 fg:15)[ ](bg:none fg:base)"
symbol="deno "
style="green"

# Prompt symbols
[character]
success_symbol = "[](green bold)"
error_symbol = "[](red)"
vicmd_symbol = "[>](cyan)"

[directory]
format = "[]($style)[$path](bg:base fg:7)[ ]($style)"
style = "bg:none fg:base"
truncation_length = 3
truncate_to_repo=true

[git_branch]
format = "[]($style)[$branch](bg:base fg:7)[ ]($style)"
style = "bg:none fg:base"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:base fg:yellow)[ ]($style)"
style = "bg:none fg:base"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "  "
untracked = "[?${count}](fg:15 bg:base)"
stashed = ""
modified = "[~${count}](fg:yellow bg:base)"
staged = "+${count}"
renamed = "»${count}"
deleted = "[${count}](fg:red bg:base)"

[cmd_duration]
min_time = 1
# duration & style
format = "[]($style)[[神](bg:base fg:flamingo bold)$duration](bg:base fg:text)[ ]($style)"
disabled = false
style = "bg:none fg:base"

[palettes.main]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "5"
mauve = "5"
red = "1"
maroon = "1"
peach = "11"
yellow = "3"
green = "2"
teal = "4"
sky = "4"
sapphire = "4"
blue = "4"
lavender = "5"
text = "7"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "15"
base = "8"
mantle = "0"
crust = "0"
