## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "main"

# Setups
format="$directory$git_branch$git_status$character"
add_newline = false

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

# Prompt symbols
[character]
success_symbol = "[](green bold)"
error_symbol = "[](red)"
vicmd_symbol = "[>](cyan)"

[directory]
format = "[]($style)[$path](bg:base fg:7)[ ]($style)"
style = "bg:none fg:base"
truncation_length = 3
truncate_to_repo=true

[git_branch]
format = "[]($style)[$branch](bg:base fg:7)[ ]($style)"
style = "bg:none fg:base"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:base fg:yellow)[ ]($style)"
style = "bg:none fg:base"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "  "
untracked = "[?${count}](fg:15 bg:base)"
stashed = ""
modified = "[~${count}](fg:yellow bg:base)"
staged = "+${count}"
renamed = "»${count}"
deleted = "[${count}](fg:red bg:base)"

[cmd_duration]
min_time = 1
# duration & style
format = "[]($style)[[神](bg:base fg:flamingo bold)$duration](bg:base fg:text)[ ]($style)"
disabled = false
style = "bg:none fg:base"

[palettes.main]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "8"
mantle = "#181825"
crust = "#11111b"
