#!/bin/sh

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment > /dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

/mnt/d/bin/sxhkdlaunch &

xset b off

/mnt/d/bin/xrdbload
xsetroot -cursor_name left_ptr
[[ -f ~/.config/X11/xmodmap ]] && xmodmap ~/.config/X11/xmodmap

/mnt/d/bin/screen

session=${1:bspwm}

case $session in
	i3|i3wm  )  exec i3 ;;
	bsp|bspwm  )  exec bspwm ;;
	rose|rose-pine  )  exec bspwm -c ~/.config/bspwm/wmrc;;
  openbox )  exec openbox-session ;;
  bspwm-gnome ) exec gnome-session-bspwm ;;
  gnome )  exec gnome-session ;;
	awesome|awesomewm  )  exec awesome ;;
	qtile )  exec qtile start ;;
	dwm )  exec /mnt/d/bin/redwm > $HOME/.startx.out.txt ;;
	*  )  exec $1 ;;
esac

exec bspwm
