#!/usr/bin/env bash

DIR="$HOME/.config/rofi"

rofi \
	-show drun \
	-modi drun \
	-no-lazy-grab \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
	-terminal wezterm \
	-theme "$DIR"/launcher.rasi
