#!/usr/bin/env bash

# pgrep -x sxhkd > /dev/null || sxhkd -c /home/comfy/.config/sxhkd/bsp &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20
bspc config top_padding         25
bspc config bottom_padding       0

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

color1="#1d2021"
bspc config normal_border_color        "$color1"
bspc config active_border_color        "$color1"
bspc config focused_border_color        "$color1"

bspc config split_ratio          0.52
bspc config center_pseudo_tiled  true
bspc config borderless_monocle   false
bspc config gapless_monocle      false

~/.config/bspwm/rules

# Autostart

# vmhgfs-fuse .host:/d /mnt/d
xrandr --output Virtual1 --mode 1920x1080
/mnt/d/bin/picomlaunch bsp
/mnt/d/bin/switch gruvbox
~/.config/polybar/scripts/adachi

/home/comfy/.ww
#/mnt/d/bin/rw /mnt/d/home/kitchen/pictures/mut-ex-wallpapers/
killall dunst; dunst &

/mnt/d/bin/bsplaunch
