#!/usr/bin/env bash

# pgrep -x sxhkd > /dev/null || sxhkd -c /home/comfy/.config/sxhkd/bsp &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20
bspc config top_padding         25

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

color1="#1d2021"
bspc config normal_border_color        "$color1"
bspc config active_border_color        "$color1"
bspc config focused_border_color        "$color1"

bspc config split_ratio          0.52
bspc config center_pseudo_tiled  true
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a \* state=pseudo_tiled
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a forest state=floating
bspc rule -a Docky layer=above manage=on border=off focus=off locked=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Autostart

# vmhgfs-fuse .host:/d /mnt/d
xrandr --output Virtual1 --mode 1920x1080
picom --config /home/comfy/.config/picom/bsp.conf &
/mnt/d/bin/bsplaunch
/home/comfy/.polybar

/home/comfy/.ww
killall dunst; dunst &
