#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding         36

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

focuse="#9ccfd8"
normal="#817c9c"
bspc config normal_border_color        "$normal"
bspc config active_border_color        "$focuse"
bspc config focused_border_color       "$focuse"

bspc config split_ratio          0.50
bspc config center_pseudo_tiled  true
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a \* state=tiled
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a forest state=floating

# Autostart

# vmhgfs-fuse .host:/d /mnt/d
xrandr --output Virtual1 --mode 1920x1080
/mnt/d/bin/picomlaunch wm
/mnt/d/bin/polylaunch wm wm-float
/mnt/d/bin/switch rose-pine-moon

#/home/comfy/.ww
/mnt/d/bin/rw /mnt/d/home/kitchen/pictures/mut-ex-wallpapers/
killall dunst; dunst &

/mnt/d/bin/wmlaunch
