#!/usr/bin/env bash

# get hayashi
echo "> INSTALLING HAYASHI <"
curl -fsSL https://raw.githubusercontent.com/CrispyBaccoon/hayashi/mega/install.sh | sh

echo "> INSTALLING HAYASHI PACKAGES < "
hayashi config init
hayashi add niru
hayashi add neovim
hayashi add tmux
hayashi add ohmyzsh

# get dotfiles
echo "> CLONING DOTFILES <"
cd
git clone https://github.com/crispybaccoon/dotfiles.git ~/.link

# setup niru
ln -s ~/.link/niru.yaml ~/.niru

echo "> LINKING DOTFILES <"
niru pull
