#!/usr/bin/env bash

mkdir -p ~/.local/bin/

export DOT_GIT=https://raw.githubusercontent.com/CrispyBaccoon/dotfiles/mega

sh -c $( curl -L ${DOT_GIT}/run/PKG )

sh -c $( curl -L ${DOT_GIT}/run/DOT )
