#!/usr/bin/env bash

# YAY
cd
git clone https://aur.archlinux.org/paru-bin.git && cd paru-bin && makepkg -si --noconfirm

# Packages
cd
packages=(
 # main
 base-devel
 git
 xorg
 zsh-git
 pulseaudio alsa-utils
 # dev
 go
 # UI
 alacritty
 bspwm
 openbox
 hsetroot
 # application
 ranger
 )

paru --noconfirm -Syu ${packages[@]}

chsh -s $(which zsh)
